version: 2
jobs:
  build:
    # directory where steps will run
    working_directory: ~/commons-lang
    docker:
      - image: daniloarcidiacono/ci-java-node:0.4.0

    steps:
      # check out source code to working directory
      - checkout

      # restore the saved cache after the first run or if `pom.xml` has changed
      - restore_cache:
          key: commons-lang-{{ checksum "pom.xml" }}

      # gets the project dependencies
      - run: mvn dependency:go-offline

      # saves the project dependencies
      - save_cache:
          paths:
            - ~/.m2
          key: commons-lang-{{ checksum "pom.xml" }}

      # Build
      - run: mvn clean package verify -Pdocs

      # Deploy
      - deploy:
          name: "Create GitHub release"
          command: |
            hub release create -a target/commons-lang-$CIRCLE_TAG-javadoc.jar -F CHANGELOG_LATEST.md $CIRCLE_TAG

      # uploads the test metadata from the `target/surefire-reports` directory so that it can show up in the CircleCI dashboard.
      - store_test_results:
          path: target/surefire-reports

      # store the jar as an artifact
      - store_artifacts:
          path: target/commons-lang-{{ .Environment.CIRCLE_TAG }}.jar

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/


